In [1]:
import numpy as np

### Array Creation

In [4]:
# Create a 1D array containing numbers from 1 to 10
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Create a 2D array (matrix) with dimensions 3x3 and fill it with random integers between 0 and 9.

array = np.random.randint(1, 10, (3,3))
array

array([[5, 4, 1],
       [4, 8, 9],
       [7, 5, 5]])

In [13]:
# Create an array of zeros with dimensions 4x5.
array = np.zeros((4,5))
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# Create an array of ones with dimensions 2x4
array = np.ones((2,4))
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# Create an identity matrix of size 5x5
array = np.identity(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Data Convertion

In [19]:
# Convert a regular Python list [3, 6, 9, 12] into a NumPy array.
list = [3, 6, 9, 12]
array = np.array(list)
array

array([ 3,  6,  9, 12])

In [23]:
# Convert a NumPy array [1.2, 3.4, 5.6] into a list.
array = np.array([1.2, 3.4, 5.6])
list = array.tolist()
print(list)
type(list)

[1.2, 3.4, 5.6]


list

In [29]:
# Convert an array of integers into an array of floats.
array = np.array([3, 4, 5, 6])
array = array.astype('float')
array.dtype

dtype('float64')

### Array Attiributes

In [35]:
# Find shape of 2D array
array = np.ones((3,5))
print('Shape: ', array.shape)
# Find dimension of array
print('Dimension: ', array.ndim)
# Calculate total elements
print('Total Elements: ', array.size)
# Find data type
print('Data Type: ', array.dtype)


Shape:  (3, 5)
Dimension:  2
Total Elements:  15
Data Type:  float64


### Array Indexing and Slicing

In [65]:
array_1d = np.array([3, 4, 5, 6, 7])
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Retrieve the second element of the 1D array
array_1d[1]

4

In [40]:
# Get the value at the position (1, 2) in the 2D array
array_2d[1,2]

7

In [41]:
# Slice the first three elements from the 1D array
array_1d[0:3]

array([3, 4, 5])

In [48]:
# Extract the second column of the 2D array.
array_2d[:,1]

array([2, 6])

In [66]:
# Create a new array that contains the last row of the 2D array
new_array = array_2d[1:, :].copy()
array_2d[(1,3)] = 9
new_array

array([[5, 6, 7, 8]])

### Array Reshaping

In [71]:
# Reshape the 1D array into a 2D array with dimensions 2x5
array_1d = np.arange(1,11)
result_1d = np.reshape(array_1d, (2,5))
result_1d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [78]:
# Flatten the 2D array to a 1D array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
result_2d = array_2d.flatten()
result_2d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
# Reshape the 2D array into a 1D array with dimensions 9x1.
new_array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
result_2d_new = np.reshape(new_array_2d, (9,1))
result_2d_new

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [90]:
# Convert the 1D array into a 3D array with dimensions 3x3x1.
array_1d = np.arange(1,10)
new_result_1d = np.reshape(array_1d, (3,3,1))
new_result_1d

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])