In [1]:
import numpy as np

### Array Creation

In [6]:
list = [1,2,3,4,5]

# Create array from a list
array = np.array(list) 

# Create an array from zeros. We can use array of zeros in matrix operations, image processing, padding(CNN)
zeros_array = np.zeros(4)
zeros_array_2d = np.zeros((3,4)) # 3 rows 4 columns

# Create an array from ones
ones_array = np.ones(4)

# Create an array with values within a specified interval
arange_array = np.arange(5) # array([0, 1, 2, 3, 4])
arange_array = np.arange(1, 9, 2) # array([1, 3, 5, 7])

# Create an array with random numbers
random_array = np.random.rand(3,4)

# Create an array wtih full of specified number
full_array = np.full((2,2),6) # first parameter is dimensions, second parameter is value

# Create an empty array
empty_array = np.empty(4)
empty_array = np.empty((2,2))
# Note: The difference between np.zeros and np.empty, np.empty does not initializes the memory but np.zeros does.

# Create an array with a defined data dtype
array1 = np.array([1,2,6], dtype='int64')

[[0.31506057 0.25743709 0.07700204 0.67604132]
 [0.95381703 0.91689759 0.95048137 0.13733218]
 [0.68061844 0.88479269 0.42467785 0.36658646]]


### NumPy Data Type Conversion

In [4]:
int_array = np.array([1,2,3,4,5])

# convert data type of int_array to float
float_array = int_array.astype('float')

### NumPy Array Attiributes

In [6]:
array = np.array([[1,2,3],[3,4,5]])

# The ndim attiribute returns the number of dimension
array.ndim # output: 2

# The size attribute returns the total number of elements
array.size # output: 6

# The shape attiribute returns a tuple that gives size of array in each dimension
array.shape # output: (2,3) -> tuple

# The dtype attiribute returns the datatype
array.dtype # output 'int64'

dtype('int64')

### NumPy Array Indexing and Slicing

In [10]:
array = np.array([2,5,1,7,2,4,8,9])
# array[start:stop:step]

array[2:6] # from index 2 to 6 -> [1, 7, 2, 4]
array[2:6:2] # from index 2 to 6 with 2 steps -> [1, 2]
array[3:] # from index 3 to end -> [7, 2, 4, 8, 9]
array[:] # from start to end ->[2, 5, 1, 7, 2, 4, 8, 9]

# MODIFY ARRAY ELEMNTS USING SLICING
numbers = np.array([2, 4, 6, 8, 10, 12])

numbers[3:] = 20 # modify elements from index 3 onwards -> [2,4,6,20,20,20]
numbers[:3] = 20 # modify the first three elements -> [20,20,20,8,10,12]
numbers[2:5] = 22 # modify elements from indices 2 to 5 -> [2,4,22,22,22,12]

array([2, 5, 1, 7, 2, 4, 8, 9])

### NumPy Array Reshaping

In [18]:
array = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# np.reshape(array, newshape, order = 'C') order is optional

# Reshape 1D Array to 2D Array
result = np.reshape(array,(4,2))

# array([[1, 3],
#        [5, 7],
#        [2, 4],
#        [6, 8]]) 

# Reshape 1D Array to 3D Array
result = np.reshape(array, (2,2,2))

# array([[[1, 3],
#         [5, 7]],

#        [[2, 4],
#         [6, 8]]])

# Flatten N-d Array to 1-D Array 

array1 = np.array([[1, 3], [5, 7], [9, 11]])
result1 = np.reshape(array1, -1) # [ 1,  3,  5,  7,  9, 11]


array([ 1,  3,  5,  7,  9, 11])